services:
  jdpc-web:
    image: nginx:1.27-alpine
    container_name: jdpc-web
    restart: unless-stopped
    ports:
      - "23456:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
